# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5923923a81df4fd976e32ca92db534f52ab19dab3305122a27c715840b269fcfec9feede22f1008b6a1105dc2cd032eaba0add007c7736d9f671ffdd3848aa1

test:
  secret_key_base: 5be80914cab6d001ac07614b09cbf65a4a56a63ad230bc70260c1f28b3646153bc8253e906e5cb795e3818bfa3be8f3ffcddc73141fb3c3abd40dc43ae0aaf2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
